refining upgrade procedure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3089,40 +3089,51 @@ fi
 # this is kludgy, but it works
 RSNAPSHOT_SYSCONFDIR=`eval echo ${sysconfdir}`
 
-# figure out if this is a fresh install or an upgrade
-# advise the user accordingly
 if test -e "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"; then
-	echo ""
-	echo "+----------------------------------------------------------------------------+"
-	echo "| A previous version of rsnapshot was detected.                              |"
-	echo "|                                                                            |"
-	echo "| It is HIGHLY recommended that you upgrade your config file for             |"
-	echo "| compatibility with this release. The only change will be that the          |"
-	echo "| \"rsync_long_args\" parameter will be explicitly set to the old default      |"
-	echo "| value from previous versions. If you have already set this parameter,      |"
-	echo "| no changes will be made.                                                   |"
-	echo "|                                                                            |"
-	echo "| If you don't upgrade your config file, rsnapshot will appear to work, but  |"
-	echo "| rearrange the relative paths to your backup files when you aren't looking. |"
-	echo "| It would be a nasty surprise, which is why we're telling you about it now. |"
-	echo "|                                                                            |"
-	echo "| If you would like to automatically upgrade your config file, just type:    |"
-	echo "|                                                                            |"
-	echo "|     \"make upgrade\"                                                         |"
-	echo "|                                                                            |"
-	echo "| After you have upgraded your config file, type:                            |"
-	echo "|                                                                            |"
-	echo "|     \"make install\"                                                         |"
-	echo "|                                                                            |"
-	echo "| to install the program.                                                    |"
-	echo "+----------------------------------------------------------------------------+"
-	echo ""
-else
-	echo ""
-	echo "Now type \"make install\" to install the program."
-	echo ""
-	echo "After rsnapshot is installed, don't forget to copy"
-	echo "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf.default to $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"
-	echo ""
+	RSNAPSHOT_OLD_VERSION=`$PERL rsnapshot-program.pl -c $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf check-config-version`
+
+	# figure out if this is a fresh install or an upgrade
+	# advise the user accordingly
+	if test "$RSNAPSHOT_OLD_VERSION" = "unknown"; then
+		echo ""
+		echo "+----------------------------------------------------------------------------+"
+		echo "| A previous version of rsnapshot was detected.                              |"
+		echo "|                                                                            |"
+		echo "| If you have not already done so, it is HIGHLY recommended that you upgrade |"
+		echo "| your config file for compatibility with this release.                      |"
+		echo "|                                                                            |"
+		echo "| If you don't upgrade your config file, rsnapshot will appear to work, but  |"
+		echo "| rearrange the relative paths to your backup files when you aren't looking. |"
+		echo "| It would be a nasty surprise, which is why we're telling you about it now. |"
+		echo "|                                                                            |"
+		echo "| If you would like to automatically upgrade your config file, just type:    |"
+		echo "|                                                                            |"
+		echo "|     \"make upgrade\"                                                         |"
+		echo "|                                                                            |"
+		echo "| After you have upgraded your config file, type \"make install\".             |"
+		echo "|                                                                            |"
+		echo "| For more information on the upgrade, read the INSTALL file that came with  |"
+		echo "| the program.                                                               |"
+		echo "+----------------------------------------------------------------------------+"
+		exit 0
+	fi
+
+	# this is already the latest version.
+	if test "$RSNAPSHOT_OLD_VERSION" = "1.2"; then
+		echo "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf found, and is up to date."
+	else
+		echo ""
+		echo "ERROR: $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf is an unknown version."
+		echo "Upgrading is not recommended until you figure out what's wrong."
+		echo ""
+		exit 1
+	fi
 fi
+
+echo ""
+echo "Now type \"make install\" to install the program."
+echo ""
+echo "After rsnapshot is installed, don't forget to copy"
+echo "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf.default to $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"
+echo ""
 
