added cmd_du

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_VERSION='1.2.0'
 PACKAGE_STRING='rsnapshot 1.2.0'
 PACKAGE_BUGREPORT='nathan@rsnapshot.org'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE PERL CMD_RSYNC RSYNC CP CMD_CP RM CMD_RM SSH CMD_SSH LOGGER CMD_LOGGER LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE PERL CMD_RSYNC RSYNC CP CMD_CP RM CMD_RM SSH CMD_SSH LOGGER CMD_LOGGER DU CMD_DU LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -797,6 +797,7 @@ Optional Packages:
   --with-rm=PATH          Specify the path to rm
   --with-ssh=PATH         Specify the path to ssh
   --with-logger=PATH      Specify the path to logger
+  --with-du=PATH          Specify the path to du
 
 Report bugs to <nathan@rsnapshot.org>.
 _ACEOF
@@ -2068,9 +2069,80 @@ fi
 	fi
 fi
 if test "$LOGGER" = "no"; then
-	SSH=/path/to/logger
+	LOGGER=/path/to/logger
 fi
 CMD_LOGGER="cmd_logger	$LOGGER"
+
+
+
+
+
+# Check whether --with-du or --without-du was given.
+if test "${with_du+set}" = set; then
+  withval="$with_du"
+
+		if test "x$withval" != "xno"; then
+			if test -x "$withval"; then
+				DU=$withval
+			else
+				{ { echo "$as_me:$LINENO: error: du not found" >&5
+echo "$as_me: error: du not found" >&2;}
+   { (exit 1); exit 1; }; }
+			fi
+		else
+			DU=no
+		fi
+
+
+fi;
+if test "$DU" != "no"; then
+	if test "$DU" = ""; then
+		# Extract the first word of "du", so it can be a program name with args.
+set dummy du; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_DU+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $DU in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_DU="$DU" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_DU="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_DU" && ac_cv_path_DU="no"
+  ;;
+esac
+fi
+DU=$ac_cv_path_DU
+
+if test -n "$DU"; then
+  echo "$as_me:$LINENO: result: $DU" >&5
+echo "${ECHO_T}$DU" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	fi
+fi
+if test "$DU" = "no"; then
+	DU=/path/to/du
+fi
+CMD_DU="cmd_du		$DU"
 
 
 
@@ -2740,6 +2812,8 @@ s,@SSH@,$SSH,;t t
 s,@CMD_SSH@,$CMD_SSH,;t t
 s,@LOGGER@,$LOGGER,;t t
 s,@CMD_LOGGER@,$CMD_LOGGER,;t t
+s,@DU@,$DU,;t t
+s,@CMD_DU@,$CMD_DU,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
