cmd_rm is back

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -775,6 +775,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-perl=PATH	  Specify the path to perl
   --with-rsync=PATH       Specify the path to rsync
+  --with-rm=PATH          Specify the path to rm
   --with-ssh=PATH         Specify the path to ssh
   --with-logger=PATH      Specify the path to logger
 
@@ -1678,6 +1679,77 @@ fi
 
 
 
+# Check whether --with-logger or --without-logger was given.
+if test "${with_logger+set}" = set; then
+  withval="$with_logger"
+
+		if test "x$withval" != "xno"; then
+			if test -x "$withval"; then
+				RM=$withval
+			else
+				{ { echo "$as_me:$LINENO: error: rm not found" >&5
+echo "$as_me: error: rm not found" >&2;}
+   { (exit 1); exit 1; }; }
+			fi
+		else
+			RM=no
+		fi
+
+
+fi;
+if test "$RM" != "no"; then
+	if test "$RM" = ""; then
+		# Extract the first word of "rm", so it can be a program name with args.
+set dummy rm; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_RM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $RM in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_RM="$RM" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_RM="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_RM" && ac_cv_path_RM="no"
+  ;;
+esac
+fi
+RM=$ac_cv_path_RM
+
+if test -n "$RM"; then
+  echo "$as_me:$LINENO: result: $RM" >&5
+echo "${ECHO_T}$RM" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	fi
+fi
+if test "$RM" = "no"; then
+	RM=/bin/rm
+fi
+CMD_RM="cmd_rm    	$RM"
+
+
+
+
+
 # Check whether --with-ssh or --without-ssh was given.
 if test "${with_ssh+set}" = set; then
   withval="$with_ssh"
@@ -2419,6 +2491,8 @@ s,@SET_MAKE@,$SET_MAKE,;t t
 s,@PERL@,$PERL,;t t
 s,@CMD_RSYNC@,$CMD_RSYNC,;t t
 s,@RSYNC@,$RSYNC,;t t
+s,@RM@,$RM,;t t
+s,@CMD_RM@,$CMD_RM,;t t
 s,@SSH@,$SSH,;t t
 s,@CMD_SSH@,$CMD_SSH,;t t
 s,@LOGGER@,$LOGGER,;t t
